listing vertex names in edgeprob
leifeld/btergm pull request #7
Opened 2018-05-09 14:10 UTC by bdesmarais

I revised the edgeprob function to include columns for the vertex names of i and j. This was in response to a request from Christiane Bjerglund. I updated the documentation as well.

2018-05-09 14:29 UTC, leifeld requested changes
Hi Bruce,

Thanks a lot for starting this pull request. I have added a few comments, mostly about formatting, in my review. There is one more thing to take into account: the `edgeprob` function is used internally in the `marginalplot` function for creating marginal effects plots. This function may need to be updated as well because the labels may otherwise be interpreted as covariates. Would you be able to do that? I think it shouldn't be a lot of work.

Thanks,

Philip

2018-05-09 14:29 UTC, leifeld commented on R/interpretation.R
>      stop(paste("The tieprob function is only applicable to ergm, btergm, and",
Write `edgeprob` instead of `tieprob`?

2018-05-09 14:29 UTC, leifeld commented on R/interpretation.R
> +  result <- c(1/(1 + exp(-lp)))
Can you preserve spaces around operators?

2018-05-09 14:29 UTC, leifeld commented on R/interpretation.R
> +    dyads.t <- dyads[which(dyads$t==t),]
Put spaces around `==`. Same multiple times below and after the `,` in `[,]`.

2018-05-11 00:21 UTC, bdesmarais commented
Thanks for the quick review, Philip! I corrected the warning message and spaces. I reviewed and tested marginalplot. I think the only way an issue would arise is if the user input "i.name" or "j.name" as one of the variable names in the call to marginalplot.

2018-05-11 09:11 UTC, leifeld commented
Thanks, Bruce. I have just reviewed the list of files you are adding. Can you remove `btergm.Rproj` and `.Rhistory`? I don't think we need them.

2018-05-14 10:05 UTC, bdesmarais commented
Just removed those files.

2018-05-14 11:33 UTC, merged

2018-05-14 11:33 UTC, leifeld commented
Thanks. I have merged it!